-- ============================================================================
--  ÔnThi — lược đồ cơ sở dữ liệu (Supabase / PostgreSQL)
--
--  Cách dùng: mở Supabase Dashboard → SQL Editor → dán toàn bộ file này → Run.
--  Chạy lại được nhiều lần (idempotent).
--
--  Bảng:
--    profiles        hồ sơ người dùng + vai trò (user/admin)
--    exam_modules    danh mục chứng chỉ (trước đây nằm cứng trong code)
--    questions       ngân hàng câu hỏi của mọi chứng chỉ
--    attempts        lịch sử từng lần làm bài
--    question_state  câu đã lưu / câu sai / câu đã thuộc, theo từng người
--    exam_sessions   bài đang làm dở, để đổi máy vẫn làm tiếp được
-- ============================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- profiles

create table if not exists public.profiles (
  id          uuid primary key references auth.users on delete cascade,
  email       text,
  display_name text,
  role        text not null default 'user' check (role in ('user', 'admin')),
  created_at  timestamptz not null default now()
);

comment on table public.profiles is 'Hồ sơ người dùng, tạo tự động khi đăng ký.';

-- Tạo hồ sơ ngay khi có tài khoản mới trong auth.users.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, ''), '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Kiểm tra vai trò admin. SECURITY DEFINER để policy trên profiles không tự gọi lại chính nó.
create or replace function public.is_admin()
returns boolean
language sql
security definer stable set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- ---------------------------------------------------------------- exam_modules

create table if not exists public.exam_modules (
  id            text primary key,
  short_name    text not null,
  short_label   text not null default '',
  full_name     text not null,
  tagline       text not null default '',
  description   text not null default '',
  icon_name     text not null default 'book',
  provider      text not null default '',
  level         text not null default '',
  exam_minutes  int  not null default 0,
  pass_note     text not null default '',
  pass_pct      int  not null default 60,
  accent_hue    int  not null default 45,
  available     boolean not null default true,
  sample_data   boolean not null default false,
  bilingual     boolean not null default false,
  highlights    jsonb not null default '[]'::jsonb,
  facts         jsonb not null default '[]'::jsonb,
  stages        jsonb not null default '[]'::jsonb,
  /*
   * Các cấp độ của chứng chỉ, ví dụ JLPT có N1..N5, HSK có HSK1..HSK6. Mỗi
   * cấp là một kỳ thi riêng biệt — thời lượng, ngưỡng đậu và ngân hàng câu
   * hỏi khác nhau. Rỗng ([]) nghĩa là chứng chỉ không chia cấp (AWS, AP, FE),
   * lúc đó dùng thẳng exam_minutes/pass_pct ở trên.
   * Dạng: [{id,label,examMinutes,passNote,passPct,sortOrder}]
   */
  levels        jsonb not null default '[]'::jsonb,
  sort_order    int  not null default 0,
  updated_at    timestamptz not null default now()
);
alter table public.exam_modules add column if not exists levels jsonb not null default '[]'::jsonb;

comment on column public.exam_modules.stages is
  'Mảng [{id,name,durationMinutes,kind,questionCount,note}] mô tả các chặng thi.';

-- ---------------------------------------------------------------- questions

create table if not exists public.questions (
  id          bigint generated by default as identity primary key,
  module_id   text not null references public.exam_modules(id) on delete cascade,
  /*
   * Cấp độ (N1, N2...) khi chứng chỉ có chia cấp — rỗng nếu không. Cùng với
   * stage_id, hai cột này xác định ĐÚNG một câu hỏi: một chứng chỉ có thể có
   * nhiều cấp, mỗi cấp có nhiều chặng thi, mỗi chặng đánh số câu từ 1.
   */
  level_id    text not null default '',
  stage_id    text not null default 'exam',
  n           int  not null,
  /*
   * 8 dạng câu hỏi. Bốn dạng đầu dùng các cột cố định bên dưới; bốn dạng mới
   * (listening/reading/writing/matching/accounting) dùng thêm cột `payload`
   * — JSONB tự do vì mỗi dạng có hình dạng dữ liệu khác hẳn nhau (audio +
   * phần/tổng phần, đoạn văn + nhiều câu con lồng nhau, số từ tối thiểu, cặp
   * ghép nối, bút toán debit/credit). Ràng buộc kiểu chặt nằm ở phía
   * TypeScript (`src/types/exam.ts`), không ở CSDL — xem chú thích payload.
   */
  kind        text not null default 'mc'
              check (kind in ('mc', 'essay', 'flashcard', 'listening', 'reading', 'writing', 'matching', 'accounting')),

  -- câu trắc nghiệm (dùng chung cho 'mc' và 'listening' — nghe xong vẫn chấm như trắc nghiệm)
  stem_en     text,
  stem_ja     text,
  options     jsonb not null default '[]'::jsonb,   -- [{label,en,ja,why?}]
  answer      text,
  multi       boolean not null default false,
  domain      text,

  -- câu tự luận (cũng dùng cho 'writing' — prompt ở đây, minWords/sampleAnswer trong payload)
  title         text,
  prompt        text,
  sub_questions jsonb not null default '[]'::jsonb, -- [{id,prompt,referenceAnswer}] (essay) hoặc câu con lồng trong 'reading'
  required      boolean not null default false,

  /*
   * Payload theo từng kind — UI đọc đúng theo `kind`, không đoán:
   *   listening : {part, totalParts, revealAfterAudio}
   *   reading   : {passageEn, passageJa} — sub_questions chứa các câu con,
   *               mỗi câu con tự có "kind": "mc" | "completion" | "matching"
   *   writing   : {minWords, sampleAnswer?}
   *   matching  : {items: [{id,label,options:[string],answerIndex}]}
   *   accounting: {accounts:[string], correctEntries:[{side:"debit"|"credit",account,amount}]}
   */
  payload     jsonb not null default '{}'::jsonb,

  created_at  timestamptz not null default now(),
  unique (module_id, level_id, stage_id, n)
);
alter table public.questions add column if not exists payload jsonb not null default '{}'::jsonb;
-- Xoá rồi tạo lại là cách "thêm ràng buộc nếu chưa có" trong Postgres — an
-- toàn chạy lại nhiều lần, và lỗi thật (nếu có) sẽ hiện ra thay vì bị nuốt.
alter table public.questions drop constraint if exists questions_kind_check;
alter table public.questions add constraint questions_kind_check
  check (kind in ('mc', 'essay', 'flashcard', 'listening', 'reading', 'writing', 'matching', 'accounting'));
alter table public.questions add column if not exists level_id text not null default '';
alter table public.questions drop constraint if exists questions_module_id_stage_id_n_key;
alter table public.questions drop constraint if exists questions_module_id_level_id_stage_id_n_key;
alter table public.questions add constraint questions_module_id_level_id_stage_id_n_key
  unique (module_id, level_id, stage_id, n);

create index if not exists questions_module_stage_idx on public.questions (module_id, stage_id, n);

-- Số liệu tổng hợp cho trang tổng quan (khỏi phải tải cả ngân hàng câu hỏi về đếm).
drop view if exists public.module_stats;
create view public.module_stats
with (security_invoker = on) as
select
  module_id,
  count(*)::int                                                                      as total,
  count(*) filter (where kind = 'mc')::int                                           as mc_total,
  count(*) filter (where kind = 'essay')::int                                        as essay_total,
  count(*) filter (where kind = 'mc' and answer is not null)::int                    as with_answer,
  count(*) filter (where kind = 'mc' and answer is not null
                     and jsonb_array_length(options) > 0)::int                       as answerable,
  count(*) filter (where multi)::int                                                 as multi_total
from public.questions
group by module_id;

-- Số liệu ngân hàng đề CHIA THEO TỪNG CẤP — dùng cho chứng chỉ có levels
-- (JLPT, HSK...). Chứng chỉ không chia cấp thì level_id = '' và số liệu ở
-- đây khớp với module_stats.
drop view if exists public.level_stats;
create view public.level_stats
with (security_invoker = on) as
select
  module_id,
  level_id,
  count(*)::int                                                                      as total,
  count(*) filter (where kind = 'mc')::int                                           as mc_total,
  count(*) filter (where kind = 'essay')::int                                        as essay_total,
  count(*) filter (where kind = 'mc' and answer is not null)::int                    as with_answer,
  count(*) filter (where kind = 'mc' and answer is not null
                     and jsonb_array_length(options) > 0)::int                       as answerable,
  count(*) filter (where multi)::int                                                 as multi_total
from public.questions
group by module_id, level_id;

-- ---------------------------------------------------------------- attempts

create table if not exists public.attempts (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users on delete cascade,
  module_id    text not null,
  -- Rỗng nếu chứng chỉ không chia cấp. Có level_id để "điểm cao nhất",
  -- "điểm trung bình" tính đúng riêng cho từng cấp thay vì gộp chung.
  level_id     text not null default '',
  stage_id     text not null default '',
  label        text not null default '',
  correct      int  not null default 0,
  total        int  not null default 0,
  pct          int  not null default 0,
  duration_sec int  not null default 0,
  passed       boolean not null default false,
  taken_at     timestamptz not null default now()
);

create index if not exists attempts_user_idx on public.attempts (user_id, taken_at desc);

-- ---------------------------------------------------------------- question_state

create table if not exists public.question_state (
  user_id     uuid not null references auth.users on delete cascade,
  module_id   text not null,
  /*
   * level_id + stage_id cùng module_id + question_n mới xác định đúng MỘT
   * câu hỏi. Thiếu hai cột này thì câu 1 buổi sáng và câu 1 buổi chiều của
   * AP (cùng module, cùng số câu, khác stage) sẽ ghi đè trạng thái của nhau —
   * đánh dấu "đã thuộc" câu 1 buổi sáng sẽ lây sang câu 1 buổi chiều. Thêm
   * cấp độ (JLPT N1..N5, mỗi cấp đều đánh số câu từ 1) sẽ nhân lỗi này lên
   * gấp bội nếu không sửa ở đây trước.
   */
  level_id    text not null default '',
  stage_id    text not null default '',
  question_n  int  not null,
  bookmarked  boolean not null default false,
  status      text check (status in ('wrong', 'mastered')),
  updated_at  timestamptz not null default now(),
  primary key (user_id, module_id, level_id, stage_id, question_n)
);
-- Cột ghi chú và các cột SM-2 (due_at, ease, reps...) được thêm bên dưới,
-- ở phần "Sáu trụ cột học tập" — không lặp lại ở đây.
-- Cho CSDL đã có bảng question_state từ trước phần vá lỗi đụng số này.
alter table public.question_state add column if not exists level_id text not null default '';
alter table public.question_state add column if not exists stage_id text not null default '';
-- Bảng đã tồn tại từ trước có thể còn khoá chính 3 cột cũ (thiếu level_id,
-- stage_id) — dựng lại cho đủ 5 cột nếu vậy. Bảng mới tạo ở trên đã đúng sẵn.
do $$
declare pk_cols int;
begin
  select array_length(conkey, 1) into pk_cols
  from pg_constraint
  where conname = 'question_state_pkey' and conrelid = 'public.question_state'::regclass;

  if pk_cols is not null and pk_cols < 5 then
    alter table public.question_state drop constraint question_state_pkey;
    alter table public.question_state add constraint question_state_pkey
      primary key (user_id, module_id, level_id, stage_id, question_n);
  end if;
end $$;

create index if not exists question_state_user_idx on public.question_state (user_id, module_id);

-- ---------------------------------------------------------------- exam_sessions

create table if not exists public.exam_sessions (
  user_id    uuid not null references auth.users on delete cascade,
  module_id  text not null,
  -- Rỗng nếu chứng chỉ không chia cấp. Có level_id trong khoá để một người
  -- có thể vừa dở bài JLPT N1 vừa dở bài JLPT N3 mà không đè lên nhau.
  level_id   text not null default '',
  payload    jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, module_id, level_id)
);
alter table public.exam_sessions add column if not exists level_id text not null default '';
do $$
declare pk_cols int;
begin
  select array_length(conkey, 1) into pk_cols
  from pg_constraint
  where conname = 'exam_sessions_pkey' and conrelid = 'public.exam_sessions'::regclass;
  if pk_cols is not null and pk_cols < 3 then
    alter table public.exam_sessions drop constraint exam_sessions_pkey;
    alter table public.exam_sessions add constraint exam_sessions_pkey
      primary key (user_id, module_id, level_id);
  end if;
end $$;

-- ============================================================================
--  Row Level Security
-- ============================================================================

alter table public.profiles       enable row level security;
alter table public.exam_modules   enable row level security;
alter table public.questions      enable row level security;
alter table public.attempts       enable row level security;
alter table public.question_state enable row level security;
alter table public.exam_sessions  enable row level security;

-- profiles: ai cũng chỉ đọc/sửa hồ sơ của mình; admin đọc được tất cả.
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
  for select using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());

/*
 * Chặn tự nâng quyền.
 *
 * Policy ở trên chỉ giới hạn được DÒNG nào sửa được, không giới hạn được CỘT —
 * nếu để nguyên thì người dùng thường sửa hồ sơ của chính mình và đổi luôn
 * `role` thành 'admin'. Hai lớp chặn:
 *   1. Quyền theo cột: `authenticated` chỉ được cập nhật `display_name`.
 *   2. Trigger: chặn mọi thay đổi `role` không đến từ admin hoặc service_role.
 */
revoke update on public.profiles from authenticated;
grant update (display_name) on public.profiles to authenticated;

create or replace function public.prevent_role_escalation()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if new.role is distinct from old.role
     and current_user <> 'service_role'
     and not public.is_admin() then
    raise exception 'Chỉ quản trị viên mới được đổi vai trò tài khoản';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_no_role_escalation on public.profiles;
create trigger profiles_no_role_escalation
  before update on public.profiles
  for each row execute function public.prevent_role_escalation();

-- Đề thi: người đã đăng nhập đọc được, chỉ admin mới sửa.
drop policy if exists modules_read on public.exam_modules;
create policy modules_read on public.exam_modules
  for select to authenticated using (true);

drop policy if exists modules_write on public.exam_modules;
create policy modules_write on public.exam_modules
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists questions_read on public.questions;
create policy questions_read on public.questions
  for select to authenticated using (true);

drop policy if exists questions_write on public.questions;
create policy questions_write on public.questions
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Dữ liệu học tập: mỗi người chỉ thấy và sửa được của chính mình.
drop policy if exists attempts_own on public.attempts;
create policy attempts_own on public.attempts
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists question_state_own on public.question_state;
create policy question_state_own on public.question_state
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists exam_sessions_own on public.exam_sessions;
create policy exam_sessions_own on public.exam_sessions
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ============================================================================
--  Quyền truy cập
-- ============================================================================

grant usage on schema public to anon, authenticated;
grant select on public.exam_modules, public.questions, public.module_stats, public.level_stats to authenticated;
grant insert, update, delete on public.exam_modules, public.questions to authenticated;
alter table public.attempts add column if not exists level_id text not null default '';
grant select, insert, update, delete on public.attempts, public.question_state, public.exam_sessions to authenticated;
grant select on public.profiles to authenticated;  -- quyền UPDATE cấp riêng theo cột ở phần RLS bên trên
grant usage, select on all sequences in schema public to authenticated;

-- ============================================================================
--  Cấp quyền admin cho tài khoản đầu tiên
--  Đăng ký tài khoản trong app trước, rồi bỏ chú thích và chạy dòng dưới:
-- ============================================================================
-- update public.profiles set role = 'admin' where email = 'ban@example.com';


-- ############################################################################
--  PHẦN 2 — Sáu trụ cột học tập
--
--  Bổ sung sau bản đầu. Chạy lại toàn bộ file này là đủ, không cần file riêng.
--
--   1. Cơ chế học theo khoa học nhận thức  -> question_state (cột SRS), responses
--   2. Cây kiến thức & bài giảng            -> topics, lessons, lesson_progress
--   3. Phân tích năng lực                   -> responses, view topic_mastery
--   4. Động lực & thói quen                 -> study_days, study_goals, user_badges
--   5. Cộng đồng & ghi chú                  -> question_comments, question_state.note
--   6. Soạn đề & đảm bảo chất lượng         -> questions (cột mới), rpc item_analysis
-- ############################################################################

-- ---------------------------------------------------------------- 2. cây kiến thức

create table if not exists public.topics (
  id          bigint generated by default as identity primary key,
  module_id   text not null references public.exam_modules(id) on delete cascade,
  parent_id   bigint references public.topics(id) on delete cascade,
  slug        text not null,
  name        text not null,
  sort_order  int not null default 0,
  unique (module_id, slug)
);

create index if not exists topics_module_idx on public.topics (module_id, sort_order);

comment on table public.topics is
  'Phân loại chi tiết (S3 Lifecycle, VPC Peering...). parent_id cho phép lồng hai cấp.';

-- ---------------------------------------------------------------- bổ sung cột cho questions

alter table public.questions add column if not exists topic_id       bigint references public.topics(id) on delete set null;
alter table public.questions add column if not exists explanation    text;
alter table public.questions add column if not exists explanation_ja text;
alter table public.questions add column if not exists explanation_vi text;
comment on column public.questions.explanation_vi is 'Giải thích đầy đủ bằng tiếng Việt — độc lập với explanation (EN) và explanation_ja (JA), không phải bản dịch máy 1-1.';
alter table public.questions add column if not exists refs           jsonb not null default '[]'::jsonb;
alter table public.questions add column if not exists body_format    text not null default 'plain';
alter table public.questions add column if not exists audio_url      text;
alter table public.questions add column if not exists difficulty     numeric;

comment on column public.questions.refs is 'Tài liệu tham khảo: [{"label":"AWS Docs","url":"https://..."}]';
comment on column public.questions.body_format is '"plain" hoặc "markdown" (markdown cho phép LaTeX $...$ và khối mã).';
comment on column public.questions.difficulty is 'Độ khó do người soạn đặt, thang -3..3 kiểu IRT. NULL = chưa đặt, dùng số liệu thực tế.';
comment on column public.questions.audio_url is 'File nghe (JLPT). Trỏ tới Supabase Storage.';

-- Giải thích cho từng phương án nằm ngay trong `options`:
--   [{"label":"A","en":"...","ja":"...","why":"Vì sao đúng/sai"}]

-- Xoá rồi tạo lại là cách duy nhất để "thêm ràng buộc nếu chưa có" trong Postgres,
-- và cũng nhờ vậy mà chạy lại file này nhiều lần vẫn được.
alter table public.questions drop constraint if exists questions_kind_check;
alter table public.questions add constraint questions_kind_check
  check (kind in ('mc', 'essay', 'flashcard'));

alter table public.questions drop constraint if exists questions_body_format_check;
alter table public.questions add constraint questions_body_format_check
  check (body_format in ('plain', 'markdown'));

-- Thẻ ghi nhớ dùng chung bảng questions với kind = 'flashcard':
--   stem_en / stem_ja = mặt trước, prompt = mặt sau.

-- ---------------------------------------------------------------- bài giảng lý thuyết

create table if not exists public.lessons (
  id          bigint generated by default as identity primary key,
  module_id   text not null references public.exam_modules(id) on delete cascade,
  topic_id    bigint references public.topics(id) on delete set null,
  slug        text not null,
  title       text not null,
  summary     text not null default '',
  body        text not null default '',
  body_format text not null default 'markdown',
  est_minutes int not null default 5,
  sort_order  int not null default 0,
  published   boolean not null default true,
  updated_at  timestamptz not null default now(),
  unique (module_id, slug)
);

create index if not exists lessons_module_idx on public.lessons (module_id, sort_order);

create table if not exists public.lesson_progress (
  user_id    uuid not null references auth.users on delete cascade,
  lesson_id  bigint not null references public.lessons(id) on delete cascade,
  status     text not null default 'reading' check (status in ('reading', 'done')),
  updated_at timestamptz not null default now(),
  primary key (user_id, lesson_id)
);

-- ---------------------------------------------------------------- 1 & 3. từng lượt trả lời

create table if not exists public.responses (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users on delete cascade,
  module_id   text not null,
  level_id    text not null default '',
  stage_id    text not null default '',
  question_n  int  not null,
  attempt_id  uuid references public.attempts(id) on delete set null,
  chosen      text,
  correct     boolean not null,
  time_ms     int,
  mode        text not null default 'practice',
  answered_at timestamptz not null default now()
);

create index if not exists responses_user_idx on public.responses (user_id, answered_at desc);
create index if not exists responses_item_idx on public.responses (module_id, level_id, question_n);
alter table public.responses add column if not exists level_id text not null default '';
create index if not exists responses_user_item_idx on public.responses (user_id, module_id, question_n);

comment on table public.responses is
  'Mỗi lượt trả lời một câu. Nguồn cho phân tích thời gian, biểu đồ năng lực, độ khó câu hỏi.';

-- ---------------------------------------------------------------- 1. lặp lại ngắt quãng (SM-2)

alter table public.question_state add column if not exists due_at           timestamptz;
alter table public.question_state add column if not exists interval_days    numeric not null default 0;
alter table public.question_state add column if not exists ease             numeric not null default 2.5;
alter table public.question_state add column if not exists reps             int not null default 0;
alter table public.question_state add column if not exists lapses           int not null default 0;
alter table public.question_state add column if not exists srs_state        text not null default 'new';
alter table public.question_state add column if not exists last_reviewed_at timestamptz;
alter table public.question_state add column if not exists note             text;

alter table public.question_state drop constraint if exists question_state_srs_check;
alter table public.question_state add constraint question_state_srs_check
  check (srs_state in ('new', 'learning', 'review', 'relearning'));

create index if not exists question_state_due_idx on public.question_state (user_id, module_id, due_at);

comment on column public.question_state.note is 'Ghi chú riêng tư của người học cho câu này.';
comment on column public.question_state.ease is 'Hệ số dễ của SM-2, tối thiểu 1.3.';

-- ---------------------------------------------------------------- 4. thói quen & mục tiêu

create table if not exists public.study_days (
  user_id        uuid not null references auth.users on delete cascade,
  day            date not null,
  questions_done int not null default 0,
  seconds        int not null default 0,
  primary key (user_id, day)
);

create table if not exists public.study_goals (
  user_id      uuid not null references auth.users on delete cascade,
  module_id    text not null,
  exam_date    date,
  daily_target int not null default 20,
  updated_at   timestamptz not null default now(),
  primary key (user_id, module_id)
);

create table if not exists public.user_badges (
  user_id   uuid not null references auth.users on delete cascade,
  code      text not null,
  earned_at timestamptz not null default now(),
  primary key (user_id, code)
);

comment on table public.user_badges is 'Danh mục huy hiệu nằm trong code (src/data/badges.ts), đây chỉ ghi ai đạt cái nào.';

-- ---------------------------------------------------------------- 5. thảo luận

create table if not exists public.question_comments (
  id         bigint generated by default as identity primary key,
  module_id  text not null,
  -- Cùng lý do như question_state: thiếu hai cột này thì bình luận câu 1
  -- buổi sáng và câu 1 buổi chiều (AP) sẽ lẫn vào cùng một luồng thảo luận.
  level_id   text not null default '',
  stage_id   text not null default '',
  question_n int  not null,
  user_id    uuid not null references auth.users on delete cascade,
  /*
   * Tên tác giả lưu thẳng ở đây thay vì nối sang `profiles`, vì RLS của
   * `profiles` chỉ cho mỗi người đọc hồ sơ của chính mình — nối sang sẽ ra
   * rỗng. Đổi tên hiển thị thì `updateDisplayName()` cập nhật lại các bình
   * luận cũ của chính người đó.
   */
  author_name text not null default 'Người học',
  parent_id  bigint references public.question_comments(id) on delete cascade,
  body       text not null check (length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted    boolean not null default false
);

create index if not exists comments_item_idx on public.question_comments (module_id, level_id, stage_id, question_n, created_at);
alter table public.question_comments add column if not exists level_id text not null default '';
alter table public.question_comments add column if not exists stage_id text not null default '';

-- Cho lần chạy lại trên CSDL đã có bảng từ trước.
alter table public.question_comments add column if not exists author_name text not null default 'Người học';

-- ---------------------------------------------------------------- khung nhìn tổng hợp

-- Mức thành thạo theo từng chủ đề, dùng vẽ biểu đồ mạng nhện. RLS lọc theo người dùng.
drop view if exists public.topic_mastery;
create view public.topic_mastery
with (security_invoker = on) as
select
  r.user_id,
  r.module_id,
  r.level_id,
  q.topic_id,
  t.name  as topic_name,
  t.slug  as topic_slug,
  count(*)::int                                                   as answered,
  count(*) filter (where r.correct)::int                           as correct,
  round(avg(case when r.correct then 1 else 0 end) * 100)::int     as pct,
  round(avg(r.time_ms))::int                                       as avg_time_ms
from public.responses r
-- Ba cột module_id + level_id + stage_id + n mới xác định đúng một câu hỏi;
-- thiếu level_id thì câu hỏi cấp N1 và N3 trùng số sẽ bị nối nhầm vào nhau.
join public.questions q
  on q.module_id = r.module_id and q.level_id = r.level_id
 and q.stage_id = r.stage_id and q.n = r.question_n
left join public.topics t on t.id = q.topic_id
group by r.user_id, r.module_id, r.level_id, q.topic_id, t.name, t.slug;

-- ---------------------------------------------------------------- 6. phân tích chất lượng câu hỏi

-- Chỉ quản trị viên đọc được, nên dùng SECURITY DEFINER kèm kiểm tra is_admin()
-- thay vì view thường (view không gắn được RLS).
/*
 * p_level / p_stage để null nghĩa là gộp tất cả các cấp/chặng lại — dùng cho
 * chứng chỉ không chia cấp. Với chứng chỉ có chia cấp (JLPT...), PHẢI truyền
 * p_level: gộp năng lực người học giữa N1 và N5 lại là vô nghĩa, vì đó là hai
 * kỳ thi đo hai thứ khác nhau. Cùng lý do đã sửa ở topic_mastery.
 */
create or replace function public.item_analysis(p_module text, p_level text default null, p_stage text default null)
returns table (
  question_n     int,
  n              int,
  p_value        numeric,   -- tỷ lệ trả lời đúng: càng cao càng dễ
  discrimination numeric,   -- chênh lệch nhóm giỏi - nhóm yếu, < 0.2 là câu kém
  avg_time_ms    int
)
language sql
security definer stable set search_path = public
as $$
  with ability as (
    select user_id, avg(case when correct then 1 else 0 end) as score
    from public.responses
    where module_id = p_module
      and (p_level is null or level_id = p_level)
      and (p_stage is null or stage_id = p_stage)
    group by user_id
  ),
  ranked as (
    select r.question_n, r.correct, r.time_ms,
           ntile(4) over (order by a.score) as quartile
    from public.responses r
    join ability a using (user_id)
    where r.module_id = p_module
      and (p_level is null or r.level_id = p_level)
      and (p_stage is null or r.stage_id = p_stage)
  )
  select
    question_n,
    count(*)::int,
    round(avg(case when correct then 1 else 0 end)::numeric, 3),
    round((
      coalesce(avg(case when quartile = 4 then (case when correct then 1 else 0 end) end), 0)
      - coalesce(avg(case when quartile = 1 then (case when correct then 1 else 0 end) end), 0)
    )::numeric, 3),
    round(avg(time_ms))::int
  from ranked
  where public.is_admin()
  group by question_n
  order by 3 asc;
$$;

-- Tỷ lệ chọn từng phương án — phát hiện câu có đáp án sai hoặc gây nhầm lẫn.
create or replace function public.option_picks(p_module text, p_n int, p_level text default null, p_stage text default null)
returns table (chosen text, n int)
language sql
security definer stable set search_path = public
as $$
  select chosen, count(*)::int
  from public.responses
  where module_id = p_module and question_n = p_n
    and (p_level is null or level_id = p_level)
    and (p_stage is null or stage_id = p_stage)
    and chosen is not null and chosen <> ''
    and public.is_admin()
  group by chosen
  order by 2 desc;
$$;

-- ############################################################################
--  RLS cho phần 2
-- ############################################################################

alter table public.topics            enable row level security;
alter table public.lessons           enable row level security;
alter table public.lesson_progress   enable row level security;
alter table public.responses         enable row level security;
alter table public.study_days        enable row level security;
alter table public.study_goals       enable row level security;
alter table public.user_badges       enable row level security;
alter table public.question_comments enable row level security;

-- Nội dung dạy học: ai đăng nhập cũng đọc được, chỉ admin sửa.
drop policy if exists topics_read on public.topics;
create policy topics_read on public.topics for select to authenticated using (true);
drop policy if exists topics_write on public.topics;
create policy topics_write on public.topics for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists lessons_read on public.lessons;
create policy lessons_read on public.lessons for select to authenticated
  using (published or public.is_admin());
drop policy if exists lessons_write on public.lessons;
create policy lessons_write on public.lessons for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Dữ liệu học tập riêng tư: chỉ chính chủ.
drop policy if exists lesson_progress_own on public.lesson_progress;
create policy lesson_progress_own on public.lesson_progress for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists responses_own on public.responses;
create policy responses_own on public.responses for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists study_days_own on public.study_days;
create policy study_days_own on public.study_days for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists study_goals_own on public.study_goals;
create policy study_goals_own on public.study_goals for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists user_badges_own on public.user_badges;
create policy user_badges_own on public.user_badges for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Thảo luận: mọi người đọc, chỉ tác giả sửa/xoá bài của mình, admin xoá được tất cả.
drop policy if exists comments_read on public.question_comments;
create policy comments_read on public.question_comments for select to authenticated using (true);
drop policy if exists comments_insert on public.question_comments;
create policy comments_insert on public.question_comments for insert to authenticated
  with check (user_id = auth.uid());
drop policy if exists comments_update on public.question_comments;
create policy comments_update on public.question_comments for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists comments_delete on public.question_comments;
create policy comments_delete on public.question_comments for delete to authenticated
  using (user_id = auth.uid() or public.is_admin());

-- ############################################################################
--  Quyền truy cập cho phần 2
-- ############################################################################

grant select on public.topics, public.lessons, public.topic_mastery to authenticated;
grant insert, update, delete on public.topics, public.lessons to authenticated;
grant select, insert, update, delete on
  public.lesson_progress, public.responses, public.study_days,
  public.study_goals, public.user_badges, public.question_comments to authenticated;
grant execute on function public.item_analysis(text, text, text) to authenticated;
grant execute on function public.option_picks(text, int, text, text) to authenticated;
-- Xoá chữ ký cũ (1-2 tham số) nếu CSDL đã có từ trước, tránh PostgREST nhập nhằng khi chọn hàm.
drop function if exists public.item_analysis(text);
drop function if exists public.option_picks(text, int);
grant usage, select on all sequences in schema public to authenticated;


-- ############################################################################
--  PHẦN 3 — Ghi chú theo đoạn văn bản được tô chọn (highlight)
--
--  Khác với question_state.note (MỘT ô ghi chú cho cả câu), đây là NHIỀU
--  điểm ghi chú gắn vào đúng đoạn văn bản người học bôi đen bằng chuột —
--  từ vựng, công thức, hay bất kỳ đoạn nào trong đề bài / phương án / giải
--  thích. Giống cách Kindle hay Medium highlight văn bản.
-- ############################################################################

create table if not exists public.question_highlights (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users on delete cascade,
  module_id    text not null,
  level_id     text not null default '',
  stage_id     text not null default '',
  question_n   int  not null,
  /*
   * Trường văn bản chứa đoạn được tô, ví dụ "stem_en", "stem_ja", "option_A",
   * "explanation". Cho phép rỗng vì bản UI hiện tại xác định vị trí tô bằng
   * DOM Range của trình duyệt tại thời điểm chọn, chưa gửi lên tên trường cụ
   * thể — để trống thay vì bắt buộc, tránh chặn phần đã làm.
   */
  field        text not null default '',
  -- Vị trí ký tự (UTF-16 code unit, tức string.length của JS) trong trường
  -- văn bản nguồn — CHO PHÉP NULL vì lý do tương tự trên. Có offset thì vẽ
  -- lại highlight chính xác sau khi tải lại trang; không có thì chỉ hiện
  -- được trong sổ tay ghi chú, không vẽ lại được đúng vị trí trong đề bài.
  start_offset int check (start_offset is null or start_offset >= 0),
  end_offset   int check (end_offset is null or start_offset is null or end_offset > start_offset),
  -- Màu tô — độc lập với "kind" (phân loại). UI hiện có 4 màu.
  color        text not null default 'yellow' check (color in ('yellow', 'green', 'pink', 'blue')),
  -- Nguyên văn đoạn đã tô.
  quote        text not null check (length(quote) between 1 and 600),
  kind         text not null default 'note' check (kind in ('vocab', 'formula', 'tip', 'note')),
  -- Ghi chú đính kèm; rỗng nghĩa là chỉ tô màu, không viết gì thêm.
  note         text not null default '' check (length(note) <= 2000),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists highlights_lookup_idx
  on public.question_highlights (user_id, module_id, level_id, stage_id, question_n);

alter table public.question_highlights enable row level security;

-- Riêng tư hoàn toàn — chỉ chính chủ đọc/sửa/xoá, không như bình luận công khai.
drop policy if exists highlights_own on public.question_highlights;
create policy highlights_own on public.question_highlights for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

grant select, insert, update, delete on public.question_highlights to authenticated;
