-- ============================================================================
--  ÔnThi — lược đồ cơ sở dữ liệu (Supabase / PostgreSQL)
--
--  Cách dùng: mở Supabase Dashboard → SQL Editor → dán toàn bộ file này → Run.
--  Chạy lại được nhiều lần (idempotent).
--
--  Bảng:
--    profiles        hồ sơ người dùng + vai trò (user/admin)
--    exam_modules    danh mục chứng chỉ (trước đây nằm cứng trong code)
--    questions       ngân hàng câu hỏi của mọi chứng chỉ
--    attempts        lịch sử từng lần làm bài
--    question_state  câu đã lưu / câu sai / câu đã thuộc, theo từng người
--    exam_sessions   bài đang làm dở, để đổi máy vẫn làm tiếp được
-- ============================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- profiles

create table if not exists public.profiles (
  id          uuid primary key references auth.users on delete cascade,
  email       text,
  display_name text,
  role        text not null default 'user' check (role in ('user', 'admin')),
  created_at  timestamptz not null default now()
);

comment on table public.profiles is 'Hồ sơ người dùng, tạo tự động khi đăng ký.';

-- Tạo hồ sơ ngay khi có tài khoản mới trong auth.users.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, ''), '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Kiểm tra vai trò admin. SECURITY DEFINER để policy trên profiles không tự gọi lại chính nó.
create or replace function public.is_admin()
returns boolean
language sql
security definer stable set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- ---------------------------------------------------------------- exam_modules

create table if not exists public.exam_modules (
  id            text primary key,
  short_name    text not null,
  short_label   text not null default '',
  full_name     text not null,
  tagline       text not null default '',
  description   text not null default '',
  icon_name     text not null default 'book',
  provider      text not null default '',
  level         text not null default '',
  exam_minutes  int  not null default 0,
  pass_note     text not null default '',
  pass_pct      int  not null default 60,
  accent_hue    int  not null default 45,
  available     boolean not null default true,
  sample_data   boolean not null default false,
  bilingual     boolean not null default false,
  highlights    jsonb not null default '[]'::jsonb,
  facts         jsonb not null default '[]'::jsonb,
  stages        jsonb not null default '[]'::jsonb,
  sort_order    int  not null default 0,
  updated_at    timestamptz not null default now()
);

comment on column public.exam_modules.stages is
  'Mảng [{id,name,durationMinutes,kind,questionCount,note}] mô tả các chặng thi.';

-- ---------------------------------------------------------------- questions

create table if not exists public.questions (
  id          bigint generated by default as identity primary key,
  module_id   text not null references public.exam_modules(id) on delete cascade,
  stage_id    text not null default 'exam',
  n           int  not null,
  kind        text not null default 'mc' check (kind in ('mc', 'essay')),

  -- câu trắc nghiệm
  stem_en     text,
  stem_ja     text,
  options     jsonb not null default '[]'::jsonb,   -- [{label,en,ja}]
  answer      text,
  multi       boolean not null default false,
  domain      text,

  -- câu tự luận
  title         text,
  prompt        text,
  sub_questions jsonb not null default '[]'::jsonb, -- [{id,prompt,referenceAnswer}]
  required      boolean not null default false,

  created_at  timestamptz not null default now(),
  unique (module_id, stage_id, n)
);

create index if not exists questions_module_stage_idx on public.questions (module_id, stage_id, n);

-- Số liệu tổng hợp cho trang tổng quan (khỏi phải tải cả ngân hàng câu hỏi về đếm).
drop view if exists public.module_stats;
create view public.module_stats
with (security_invoker = on) as
select
  module_id,
  count(*)::int                                                                      as total,
  count(*) filter (where kind = 'mc')::int                                           as mc_total,
  count(*) filter (where kind = 'essay')::int                                        as essay_total,
  count(*) filter (where kind = 'mc' and answer is not null)::int                    as with_answer,
  count(*) filter (where kind = 'mc' and answer is not null
                     and jsonb_array_length(options) > 0)::int                       as answerable,
  count(*) filter (where multi)::int                                                 as multi_total
from public.questions
group by module_id;

-- ---------------------------------------------------------------- attempts

create table if not exists public.attempts (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users on delete cascade,
  module_id    text not null,
  stage_id     text not null default '',
  label        text not null default '',
  correct      int  not null default 0,
  total        int  not null default 0,
  pct          int  not null default 0,
  duration_sec int  not null default 0,
  passed       boolean not null default false,
  taken_at     timestamptz not null default now()
);

create index if not exists attempts_user_idx on public.attempts (user_id, taken_at desc);

-- ---------------------------------------------------------------- question_state

create table if not exists public.question_state (
  user_id     uuid not null references auth.users on delete cascade,
  module_id   text not null,
  question_n  int  not null,
  bookmarked  boolean not null default false,
  status      text check (status in ('wrong', 'mastered')),
  updated_at  timestamptz not null default now(),
  primary key (user_id, module_id, question_n)
);

create index if not exists question_state_user_idx on public.question_state (user_id, module_id);

-- ---------------------------------------------------------------- exam_sessions

create table if not exists public.exam_sessions (
  user_id    uuid not null references auth.users on delete cascade,
  module_id  text not null,
  payload    jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, module_id)
);

-- ============================================================================
--  Row Level Security
-- ============================================================================

alter table public.profiles       enable row level security;
alter table public.exam_modules   enable row level security;
alter table public.questions      enable row level security;
alter table public.attempts       enable row level security;
alter table public.question_state enable row level security;
alter table public.exam_sessions  enable row level security;

-- profiles: ai cũng chỉ đọc/sửa hồ sơ của mình; admin đọc được tất cả.
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
  for select using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());

/*
 * Chặn tự nâng quyền.
 *
 * Policy ở trên chỉ giới hạn được DÒNG nào sửa được, không giới hạn được CỘT —
 * nếu để nguyên thì người dùng thường sửa hồ sơ của chính mình và đổi luôn
 * `role` thành 'admin'. Hai lớp chặn:
 *   1. Quyền theo cột: `authenticated` chỉ được cập nhật `display_name`.
 *   2. Trigger: chặn mọi thay đổi `role` không đến từ admin hoặc service_role.
 */
revoke update on public.profiles from authenticated;
grant update (display_name) on public.profiles to authenticated;

create or replace function public.prevent_role_escalation()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if new.role is distinct from old.role
     and current_user <> 'service_role'
     and not public.is_admin() then
    raise exception 'Chỉ quản trị viên mới được đổi vai trò tài khoản';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_no_role_escalation on public.profiles;
create trigger profiles_no_role_escalation
  before update on public.profiles
  for each row execute function public.prevent_role_escalation();

-- Đề thi: người đã đăng nhập đọc được, chỉ admin mới sửa.
drop policy if exists modules_read on public.exam_modules;
create policy modules_read on public.exam_modules
  for select to authenticated using (true);

drop policy if exists modules_write on public.exam_modules;
create policy modules_write on public.exam_modules
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists questions_read on public.questions;
create policy questions_read on public.questions
  for select to authenticated using (true);

drop policy if exists questions_write on public.questions;
create policy questions_write on public.questions
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Dữ liệu học tập: mỗi người chỉ thấy và sửa được của chính mình.
drop policy if exists attempts_own on public.attempts;
create policy attempts_own on public.attempts
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists question_state_own on public.question_state;
create policy question_state_own on public.question_state
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists exam_sessions_own on public.exam_sessions;
create policy exam_sessions_own on public.exam_sessions
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ============================================================================
--  Quyền truy cập
-- ============================================================================

grant usage on schema public to anon, authenticated;
grant select on public.exam_modules, public.questions, public.module_stats to authenticated;
grant insert, update, delete on public.exam_modules, public.questions to authenticated;
grant select, insert, update, delete on public.attempts, public.question_state, public.exam_sessions to authenticated;
grant select on public.profiles to authenticated;  -- quyền UPDATE cấp riêng theo cột ở phần RLS bên trên
grant usage, select on all sequences in schema public to authenticated;

-- ============================================================================
--  Cấp quyền admin cho tài khoản đầu tiên
--  Đăng ký tài khoản trong app trước, rồi bỏ chú thích và chạy dòng dưới:
-- ============================================================================
-- update public.profiles set role = 'admin' where email = 'ban@example.com';


-- ############################################################################
--  PHẦN 2 — Sáu trụ cột học tập
--
--  Bổ sung sau bản đầu. Chạy lại toàn bộ file này là đủ, không cần file riêng.
--
--   1. Cơ chế học theo khoa học nhận thức  -> question_state (cột SRS), responses
--   2. Cây kiến thức & bài giảng            -> topics, lessons, lesson_progress
--   3. Phân tích năng lực                   -> responses, view topic_mastery
--   4. Động lực & thói quen                 -> study_days, study_goals, user_badges
--   5. Cộng đồng & ghi chú                  -> question_comments, question_state.note
--   6. Soạn đề & đảm bảo chất lượng         -> questions (cột mới), rpc item_analysis
-- ############################################################################

-- ---------------------------------------------------------------- 2. cây kiến thức

create table if not exists public.topics (
  id          bigint generated by default as identity primary key,
  module_id   text not null references public.exam_modules(id) on delete cascade,
  parent_id   bigint references public.topics(id) on delete cascade,
  slug        text not null,
  name        text not null,
  sort_order  int not null default 0,
  unique (module_id, slug)
);

create index if not exists topics_module_idx on public.topics (module_id, sort_order);

comment on table public.topics is
  'Phân loại chi tiết (S3 Lifecycle, VPC Peering...). parent_id cho phép lồng hai cấp.';

-- ---------------------------------------------------------------- bổ sung cột cho questions

alter table public.questions add column if not exists topic_id       bigint references public.topics(id) on delete set null;
alter table public.questions add column if not exists explanation    text;
alter table public.questions add column if not exists explanation_ja text;
alter table public.questions add column if not exists refs           jsonb not null default '[]'::jsonb;
alter table public.questions add column if not exists body_format    text not null default 'plain';
alter table public.questions add column if not exists audio_url      text;
alter table public.questions add column if not exists difficulty     numeric;

comment on column public.questions.refs is 'Tài liệu tham khảo: [{"label":"AWS Docs","url":"https://..."}]';
comment on column public.questions.body_format is '"plain" hoặc "markdown" (markdown cho phép LaTeX $...$ và khối mã).';
comment on column public.questions.difficulty is 'Độ khó do người soạn đặt, thang -3..3 kiểu IRT. NULL = chưa đặt, dùng số liệu thực tế.';
comment on column public.questions.audio_url is 'File nghe (JLPT). Trỏ tới Supabase Storage.';

-- Giải thích cho từng phương án nằm ngay trong `options`:
--   [{"label":"A","en":"...","ja":"...","why":"Vì sao đúng/sai"}]

-- Xoá rồi tạo lại là cách duy nhất để "thêm ràng buộc nếu chưa có" trong Postgres,
-- và cũng nhờ vậy mà chạy lại file này nhiều lần vẫn được.
alter table public.questions drop constraint if exists questions_kind_check;
alter table public.questions add constraint questions_kind_check
  check (kind in ('mc', 'essay', 'flashcard'));

alter table public.questions drop constraint if exists questions_body_format_check;
alter table public.questions add constraint questions_body_format_check
  check (body_format in ('plain', 'markdown'));

-- Thẻ ghi nhớ dùng chung bảng questions với kind = 'flashcard':
--   stem_en / stem_ja = mặt trước, prompt = mặt sau.

-- ---------------------------------------------------------------- bài giảng lý thuyết

create table if not exists public.lessons (
  id          bigint generated by default as identity primary key,
  module_id   text not null references public.exam_modules(id) on delete cascade,
  topic_id    bigint references public.topics(id) on delete set null,
  slug        text not null,
  title       text not null,
  summary     text not null default '',
  body        text not null default '',
  body_format text not null default 'markdown',
  est_minutes int not null default 5,
  sort_order  int not null default 0,
  published   boolean not null default true,
  updated_at  timestamptz not null default now(),
  unique (module_id, slug)
);

create index if not exists lessons_module_idx on public.lessons (module_id, sort_order);

create table if not exists public.lesson_progress (
  user_id    uuid not null references auth.users on delete cascade,
  lesson_id  bigint not null references public.lessons(id) on delete cascade,
  status     text not null default 'reading' check (status in ('reading', 'done')),
  updated_at timestamptz not null default now(),
  primary key (user_id, lesson_id)
);

-- ---------------------------------------------------------------- 1 & 3. từng lượt trả lời

create table if not exists public.responses (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users on delete cascade,
  module_id   text not null,
  stage_id    text not null default '',
  question_n  int  not null,
  attempt_id  uuid references public.attempts(id) on delete set null,
  chosen      text,
  correct     boolean not null,
  time_ms     int,
  mode        text not null default 'practice',
  answered_at timestamptz not null default now()
);

create index if not exists responses_user_idx on public.responses (user_id, answered_at desc);
create index if not exists responses_item_idx on public.responses (module_id, question_n);
create index if not exists responses_user_item_idx on public.responses (user_id, module_id, question_n);

comment on table public.responses is
  'Mỗi lượt trả lời một câu. Nguồn cho phân tích thời gian, biểu đồ năng lực, độ khó câu hỏi.';

-- ---------------------------------------------------------------- 1. lặp lại ngắt quãng (SM-2)

alter table public.question_state add column if not exists due_at           timestamptz;
alter table public.question_state add column if not exists interval_days    numeric not null default 0;
alter table public.question_state add column if not exists ease             numeric not null default 2.5;
alter table public.question_state add column if not exists reps             int not null default 0;
alter table public.question_state add column if not exists lapses           int not null default 0;
alter table public.question_state add column if not exists srs_state        text not null default 'new';
alter table public.question_state add column if not exists last_reviewed_at timestamptz;
alter table public.question_state add column if not exists note             text;

alter table public.question_state drop constraint if exists question_state_srs_check;
alter table public.question_state add constraint question_state_srs_check
  check (srs_state in ('new', 'learning', 'review', 'relearning'));

create index if not exists question_state_due_idx on public.question_state (user_id, module_id, due_at);

comment on column public.question_state.note is 'Ghi chú riêng tư của người học cho câu này.';
comment on column public.question_state.ease is 'Hệ số dễ của SM-2, tối thiểu 1.3.';

-- ---------------------------------------------------------------- 4. thói quen & mục tiêu

create table if not exists public.study_days (
  user_id        uuid not null references auth.users on delete cascade,
  day            date not null,
  questions_done int not null default 0,
  seconds        int not null default 0,
  primary key (user_id, day)
);

create table if not exists public.study_goals (
  user_id      uuid not null references auth.users on delete cascade,
  module_id    text not null,
  exam_date    date,
  daily_target int not null default 20,
  updated_at   timestamptz not null default now(),
  primary key (user_id, module_id)
);

create table if not exists public.user_badges (
  user_id   uuid not null references auth.users on delete cascade,
  code      text not null,
  earned_at timestamptz not null default now(),
  primary key (user_id, code)
);

comment on table public.user_badges is 'Danh mục huy hiệu nằm trong code (src/data/badges.ts), đây chỉ ghi ai đạt cái nào.';

-- ---------------------------------------------------------------- 5. thảo luận

create table if not exists public.question_comments (
  id         bigint generated by default as identity primary key,
  module_id  text not null,
  question_n int  not null,
  user_id    uuid not null references auth.users on delete cascade,
  parent_id  bigint references public.question_comments(id) on delete cascade,
  body       text not null check (length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted    boolean not null default false
);

create index if not exists comments_item_idx on public.question_comments (module_id, question_n, created_at);

-- ---------------------------------------------------------------- khung nhìn tổng hợp

-- Mức thành thạo theo từng chủ đề, dùng vẽ biểu đồ mạng nhện. RLS lọc theo người dùng.
drop view if exists public.topic_mastery;
create view public.topic_mastery
with (security_invoker = on) as
select
  r.user_id,
  r.module_id,
  q.topic_id,
  t.name  as topic_name,
  t.slug  as topic_slug,
  count(*)::int                                                   as answered,
  count(*) filter (where r.correct)::int                           as correct,
  round(avg(case when r.correct then 1 else 0 end) * 100)::int     as pct,
  round(avg(r.time_ms))::int                                       as avg_time_ms
from public.responses r
join public.questions q
  on q.module_id = r.module_id and q.stage_id = r.stage_id and q.n = r.question_n
left join public.topics t on t.id = q.topic_id
group by r.user_id, r.module_id, q.topic_id, t.name, t.slug;

-- ---------------------------------------------------------------- 6. phân tích chất lượng câu hỏi

-- Chỉ quản trị viên đọc được, nên dùng SECURITY DEFINER kèm kiểm tra is_admin()
-- thay vì view thường (view không gắn được RLS).
create or replace function public.item_analysis(p_module text)
returns table (
  question_n     int,
  n              int,
  p_value        numeric,   -- tỷ lệ trả lời đúng: càng cao càng dễ
  discrimination numeric,   -- chênh lệch nhóm giỏi - nhóm yếu, < 0.2 là câu kém
  avg_time_ms    int
)
language sql
security definer stable set search_path = public
as $$
  with ability as (
    select user_id, avg(case when correct then 1 else 0 end) as score
    from public.responses where module_id = p_module group by user_id
  ),
  ranked as (
    select r.question_n, r.correct, r.time_ms,
           ntile(4) over (order by a.score) as quartile
    from public.responses r
    join ability a using (user_id)
    where r.module_id = p_module
  )
  select
    question_n,
    count(*)::int,
    round(avg(case when correct then 1 else 0 end)::numeric, 3),
    round((
      coalesce(avg(case when quartile = 4 then (case when correct then 1 else 0 end) end), 0)
      - coalesce(avg(case when quartile = 1 then (case when correct then 1 else 0 end) end), 0)
    )::numeric, 3),
    round(avg(time_ms))::int
  from ranked
  where public.is_admin()
  group by question_n
  order by 3 asc;
$$;

-- Tỷ lệ chọn từng phương án — phát hiện câu có đáp án sai hoặc gây nhầm lẫn.
create or replace function public.option_picks(p_module text, p_n int)
returns table (chosen text, n int)
language sql
security definer stable set search_path = public
as $$
  select chosen, count(*)::int
  from public.responses
  where module_id = p_module and question_n = p_n
    and chosen is not null and chosen <> ''
    and public.is_admin()
  group by chosen
  order by 2 desc;
$$;

-- ############################################################################
--  RLS cho phần 2
-- ############################################################################

alter table public.topics            enable row level security;
alter table public.lessons           enable row level security;
alter table public.lesson_progress   enable row level security;
alter table public.responses         enable row level security;
alter table public.study_days        enable row level security;
alter table public.study_goals       enable row level security;
alter table public.user_badges       enable row level security;
alter table public.question_comments enable row level security;

-- Nội dung dạy học: ai đăng nhập cũng đọc được, chỉ admin sửa.
drop policy if exists topics_read on public.topics;
create policy topics_read on public.topics for select to authenticated using (true);
drop policy if exists topics_write on public.topics;
create policy topics_write on public.topics for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists lessons_read on public.lessons;
create policy lessons_read on public.lessons for select to authenticated
  using (published or public.is_admin());
drop policy if exists lessons_write on public.lessons;
create policy lessons_write on public.lessons for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Dữ liệu học tập riêng tư: chỉ chính chủ.
drop policy if exists lesson_progress_own on public.lesson_progress;
create policy lesson_progress_own on public.lesson_progress for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists responses_own on public.responses;
create policy responses_own on public.responses for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists study_days_own on public.study_days;
create policy study_days_own on public.study_days for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists study_goals_own on public.study_goals;
create policy study_goals_own on public.study_goals for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists user_badges_own on public.user_badges;
create policy user_badges_own on public.user_badges for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Thảo luận: mọi người đọc, chỉ tác giả sửa/xoá bài của mình, admin xoá được tất cả.
drop policy if exists comments_read on public.question_comments;
create policy comments_read on public.question_comments for select to authenticated using (true);
drop policy if exists comments_insert on public.question_comments;
create policy comments_insert on public.question_comments for insert to authenticated
  with check (user_id = auth.uid());
drop policy if exists comments_update on public.question_comments;
create policy comments_update on public.question_comments for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists comments_delete on public.question_comments;
create policy comments_delete on public.question_comments for delete to authenticated
  using (user_id = auth.uid() or public.is_admin());

-- ############################################################################
--  Quyền truy cập cho phần 2
-- ############################################################################

grant select on public.topics, public.lessons, public.topic_mastery to authenticated;
grant insert, update, delete on public.topics, public.lessons to authenticated;
grant select, insert, update, delete on
  public.lesson_progress, public.responses, public.study_days,
  public.study_goals, public.user_badges, public.question_comments to authenticated;
grant execute on function public.item_analysis(text) to authenticated;
grant execute on function public.option_picks(text, int) to authenticated;
grant usage, select on all sequences in schema public to authenticated;
